import { Question } from "@/types/questions.type";

export const questions: Question[] = [
    {
      step: 1,
      category: "Baseline info",
      stepOf: "Step 1 of 10",
      progress: 10,
      icon: "👤",
      question: "How old are you?",
      subtitle: "Age changes how your body handles sugar and blood pressure.",
      type: "age",
      hasInput: true,
      options: [
        { label: "Under 30", value: "under30" },
        { label: "30 to 44", value: "30-44" },
        { label: "45 to 59", value: "45-59" },
        { label: "60 or older", value: "60plus" },
      ],
      inputPlaceholder: "For example, 45",
      inputLabel: "Or enter your exact age",
      inputUnit: "Years",
    },
    {
      step: 2,
      category: "Baseline info",
      stepOf: "Step 2 of 10",
      progress: 20,
      icon: "👥",
      question: "What is your gender?",
      subtitle: "Some risks are a bit different for men and women.",
      type: "gender",
      options: [
        { label: "Female", value: "female" },
        { label: "Male", value: "male" },
        { label: "Another term", value: "other" },
      ],
    },
    {
      step: 3,
      category: "Baseline info",
      stepOf: "Step 3 of 10",
      progress: 30,
      icon: "📏",
      question: "What is your height and weight?",
      subtitle: "This helps us estimate your body mass index (BMI).",
      type: "measurements",
      hasDoubleInput: true,
      inputs: [
        {
          label: "Height",
          placeholder: "For example, 165",
          unit: "Centimetres (cm)",
        },
        {
          label: "Weight",
          placeholder: "For example, 70",
          unit: "Kilograms (Kg)",
        },
      ],
      note: "We quietly estimate your BMI from this. It is just one part of your overall picture.",
    },
    {
      step: 4,
      category: "Baseline info",
      stepOf: "Step 4 of 10",
      progress: 40,
      icon: "📐",
      question: "What is your waist size?",
      subtitle: "Waist size shows how much fat sits around your middle....",
      type: "waist",
      hasInput: true,
      inputPlaceholder: "For example, 165",
      inputLabel: "Waist size",
      inputUnit: "Around your belly button, in cm",
      note: "If you do not know, a quick guess is okay for now.",
    },
    {
      step: 5,
      category: "Shared info",
      stepOf: "Step 5 of 10",
      progress: 50,
      icon: "🏃",
      question: "How active are you most days?",
      subtitle: "How do you actively do movements during the day",
      type: "activity",
      options: [
        {
          label: "Mostly sitting",
          value: "sitting",
          description: "Desk work, very little walking",
        },
        {
          label: "Some walking",
          value: "walking",
          description: "Short walks or light chores most days",
        },
        {
          label: "Regularly active",
          value: "regular",
          description: "30+ minutes of movement most days",
        },
        {
          label: "Very active",
          value: "very",
          description: "Hard exercise or heavy work",
        },
      ],
    },
    {
      step: 6,
      category: "Shared info",
      stepOf: "Step 6 of 10",
      progress: 20,
      icon: "🍽️",
      question: "How would you describe your usual eating habits?",
      subtitle: "Which kind of meals do you usually take",
      type: "eating",
      options: [
        { label: "Many fast foods or sugary drinks", value: "fast" },
        { label: "Mix of fresh and processed foods", value: "mix" },
        {
          label: "I eat vegetables and fruits most of the days",
          value: "healthy",
        },
        { label: "Home-cooked and balanced", value: "homecooked" },
      ],
    },
    {
      step: 7,
      category: "Shared info",
      stepOf: "Step 6 of 10",
      progress: 20,
      icon: "🍽️",
      question: "How would you describe your usual eating habits?",
      subtitle: 'What we mean by "Eating Habits"',
      type: "eatingWithImages",
      hasImages: true,
      options: [
        {
          label: "Many fast foods or sugary drinks",
          value: "fast",
          image: "🍔🍕🍟",
          examples: [
            "Fried foods (chips, kebabs, fried chicken)",
            "Sugary drinks (soda, energy drinks)",
            "Fast-food meals (burgers, pizza)",
          ],
        },
        {
          label: "I eat vegetables and fruits most days",
          value: "healthy",
          image: "🥗🥕🍎",
          examples: [
            "Vegetables (spinach, cabbage, carrots)",
            "Fruits (bananas, mangoes, oranges)",
            "(Image: Small plate of fruits & veggies)",
          ],
        },
        {
          label: "Mix of fresh and processed foods",
          value: "mix",
          image: "🍱🥘",
          examples: [
            "Home meals + snacks (biscuits, instant noodles)",
            "Occasional take-away meals",
          ],
        },
        {
          label: "Home-cooked and balanced",
          value: "homecooked",
          image: "🍚🥘🥗",
          examples: [
            "Rice + beans + vegetables",
            "Ugali + greens",
            "Eggs + salad",
          ],
        },
      ],
    },
    {
      step: 8,
      category: "Specific info",
      stepOf: "Step 8 of 10",
      progress: 80,
      icon: "🩸",
      question: "Have you ever been told you had high blood sugar?",
      subtitle: "Past high readings can be an early warning sign.",
      type: "bloodSugar",
      options: [
        {
          label: "Yes",
          value: "yes",
          description: "Told you had prediabetes or high",
        },
        { label: "No", value: "no", description: "Never told this before" },
        { label: "Not sure", value: "notsure", description: "Do not remember" },
      ],
    },
    {
      step: 9,
      category: "Specific info",
      stepOf: "Step 9 of 10",
      progress: 90,
      icon: "🧂",
      question: "How often do you add extra salt to your food?",
      subtitle: "Too much salt can push blood pressure up.",
      type: "salt",
      options: [
        {
          label: "Often",
          value: "often",
          description: "Add salt at most meals",
        },
        { label: "No", value: "no", description: "Add salt a few times" },
        {
          label: "Not sure",
          value: "notsure",
          description: "Rarely add extra salt",
        },
      ],
    },
    {
      step: 10,
      category: "Specific info",
      stepOf: "Step 10 of 10",
      progress: 90,
      icon: "💊",
      question: "Do you take medicine for blood pressure now?",
      subtitle: "Blood pressure pills show that your pressure has been high.",
      type: "medication",
      options: [
        {
          label: "Yes",
          value: "yes",
          description: "You take blood pressure pills",
        },
        { label: "No", value: "no", description: "You do not take them" },
      ],
    },
  ];